### PR TITLE
rawtext

### LINKED ISSUE #6: Incorrect escaping inside STYLE and SCRIPT elements.
STYLE and SCRIPT elements have special behavior regarding escaping: they use “RAWTEXT” rather than “DATA” mode. For example, this is not an ampersand character reference:

```js
html`<script>hello&amp;</script>`
```

I think this means we’ll need to track the element name when we enter the DATA state, and if it’s STYLE or SCRIPT, enter the RAWTEXT state instead. And then likewise we’ll have to handle the “appropriate end tag” to determine when we exit the RAWTEXT state.

### LINKED ISSUE #18: Can’t set value of textarea by (only) interpolation
Attempting to interpolate anything into a textarea:

    html`<textarea>${"hello"}</textarea>`

Produces a textarea with the value `"<!--::1-->"`

image

(Which I guess is not terribly surprising since the "child is the value" behavior of textareas seems pretty nonstandard!)

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #6.
Fixes #18.
Fixes #21.

Note that there’s no way to safely interpolate a value such as `"</script>"` into a script element (an “appropriate” end tag in a non-escapable raw text element), so this case now throws an error.

/cc @tomlarkworthy

### CODE REVIEW

File: test/snapshots.js [hunk 1]
```diff
@@ -33,33 +33,23 @@ export function interpolatedNumber() {
...
-  // return html`<textarea>${"value"}</textarea>`;
-  return html`<textarea>value</textarea>`;
+  return html`<textarea>${"value"}</textarea>`;
 }
 
 export function interpolateIntoTitle() {
-  // TODO https://github.com/observablehq/htl/issues/18
-  // return html`<title>${"value"}</title>`;
-  return html`<title>value</title>`;
+  return html`<title>${"value"}</title>`;
```
Comment (tomlarkworthy) [inline test/snapshots.js:52]: FYI, a case that works for yours and not the hack I did earlier would be 2 sequential interpolations

html`<title>${"value"}${"value"}</title>`;

**Review by tomlarkworthy — APPROVED** [review]
Very neat.

**Comment by mbostock** [comment]
I’m *almost* there. I implemented the appropriate end tag check, and now distinguish between escapable and non-escapable raw text elements. The problem with the non-escapable raw text elements (style and script) is that I need to enforce that the interpolated value doesn’t contain an appropriate end tag so that you can’t change the structure of the DOM. I.e., this should be disallowed:

```js
html`<script>${"</script>"}</script>`
```

That’s easy enough to do here:

https://github.com/observablehq/htl/blob/cce4eeb7d0f5d2422bbcf012a670c8f30712ed2a/src/index.js#L105-L106

Except that it doesn’t handle the case where the interpolated value combines with other content to form an appropriate end tag, such as this:

```js
html`<script>${"</scr"}${"ipt>"}</script>`
```

I’ll try to fix this (not that it’s ever a good idea to interpolate into a script or style tag).
